FROM golang:latest AS builder
ENV GOPROXY https://goproxy.cn
WORKDIR /src
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest
COPY ./feed_srv.yaml /
COPY --from=builder /src/app /
ENTRYPOINT ["/app"]
